### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#88]
**Description**
This is the pre-launch checklist for Move.

**Acceptance Criteria**
From other issues, plus known work on infrastructure:
- [ ] replication is back up and running, using ETL stack with EFS mount as storage;
- [x] vector tiles are being generated to `/data`, which is mapped to `move.intra.dev-toronto.ca/tiles`;
- [x] dev dataset has been re-generated with timestamps, and scp'd to development laptop;
- [x] deployment has been tested on `move.intra.dev-toronto.ca`;
- [x] review, approve, and merge @chelsrosic 's work on #75 ;
- [x] re-generate vector tiles using @chelsrosic 's work;
- [x] disable Request Data and Track Requests sections of the site;
- [x] implement tabular TMC report in show reports modal;
- [x] add Zendesk chat.

From design review and informal feedback:
- [ ] button states: make hover, active clearer;
- [x] add icons to status boxes in `FcCardTableCounts`;
- [x] reduce `font-size` on `FcCardTable` headers;
- [x] grey `background-color` on `.sorted` headers in `FcCardTable`;
- [ ] increase size of action bar, and bump up prominence of "Request Study" button;
- [x] switch to "sentence case" in location search bar;
- [x] add marker on map to indicate location selection;
- [x] switch back to dark grey map tiles, and update colors of layers to maintain contrast;
- [x] reduce `font-size` in top bar;
- [x] `s/Move/MOVE/g` for product name;
- [ ] add chevrons on `TdsButtonDropdown`;
- [x] move text on login screen to right column;
- [ ] add day of week beside `FcCardTableCounts` dates;
- [ ] text popups on selected location?

Thanks to everyone who took some time to test it!
